// Docusaurus site for LLMClick. Every page under docs/ is generated by scripts/sync.py from the repository's
// README files and code; edit those, or the intros under intros/, never docs/ itself.
const {themes} = require('prism-react-renderer');

/** @type {import('@docusaurus/types').Config} */
module.exports = {
  title: 'LLMClick',
  tagline: 'Config-driven custom model building: one YAML per model, one pipeline per recipe',
  favicon: 'img/favicon.svg',
  url: 'https://ash-hun.github.io',
  baseUrl: '/LLMClick/',
  organizationName: 'ash-hun',
  projectName: 'LLMClick',
  trailingSlash: false,
  onBrokenLinks: 'throw',
  markdown: {format: 'detect', hooks: {onBrokenMarkdownLinks: 'warn'}},
  i18n: {defaultLocale: 'en', locales: ['en']},
  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'docs',
          routeBasePath: '/',
          sidebarPath: './sidebars.js',
          editUrl: 'https://github.com/ash-hun/LLMClick/edit/main/',
          showLastUpdateTime: false,
        },
        blog: false,
        theme: {customCss: './src/css/custom.css'},
      }),
    ],
  ],
  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {respectPrefersColorScheme: true},
      navbar: {
        title: 'LLMClick',
        items: [
          {type: 'docSidebar', sidebarId: 'docs', position: 'left', label: 'Docs'},
          {to: '/reference/recipes', label: 'Reference', position: 'left'},
          {href: 'https://github.com/ash-hun/LLMClick', label: 'GitHub', position: 'right'},
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {title: 'Docs', items: [{label: 'Quick start', to: '/quick-start'}, {label: 'Reference', to: '/reference/recipes'}]},
          {title: 'Project', items: [{label: 'GitHub', href: 'https://github.com/ash-hun/LLMClick'}]},
        ],
        copyright: 'LLMClick is MIT licensed. Models and datasets a config names keep their own licences.',
      },
      prism: {
        theme: themes.github,
        darkTheme: themes.dracula,
        additionalLanguages: ['bash', 'yaml', 'python', 'json'],
      },
    }),
};
